import {
  House,
  ShoppingCart,
  Utensils,
  Car,
  Receipt,
  HeartPulse,
  GraduationCap,
  Gamepad2,
  Briefcase,
  Banknote,
  Plane,
  Package,
} from "lucide-react";

export const Icons = [
  {
    name: "utensils",
    icon: Utensils,
    textColor: "text-orange-500",
    hoverBg: "hover:bg-orange-100 hover:border-orange-300",
    selectedBg: "bg-orange-100 border-orange-300",
  },
  {
    name: "shopping-cart",
    icon: ShoppingCart,
    textColor: "text-green-500",
    hoverBg: "hover:bg-green-100 hover:border-green-300",
    selectedBg: "bg-green-100 border-green-300",
  },
  {
    name: "car",
    icon: Car,
    textColor: "text-blue-500",
    hoverBg: "hover:bg-blue-100 hover:border-blue-300",
    selectedBg: "bg-blue-100 border-blue-300",
  },
  {
    name: "house",
    icon: House,
    textColor: "text-purple-500",
    hoverBg: "hover:bg-purple-100 hover:border-purple-300",
    selectedBg: "bg-purple-100 border-purple-300",
  },
  {
    name: "receipt",
    icon: Receipt,
    textColor: "text-yellow-500",
    hoverBg: "hover:bg-yellow-100 hover:border-yellow-300",
    selectedBg: "bg-yellow-100 border-yellow-300",
  },
  {
    name: "heart-pulse",
    icon: HeartPulse,
    textColor: "text-red-500",
    hoverBg: "hover:bg-red-100 hover:border-red-300",
    selectedBg: "bg-red-100 border-red-300",
  },
  {
    name: "graduation-cap",
    icon: GraduationCap,
    textColor: "text-indigo-500",
    hoverBg: "hover:bg-indigo-100 hover:border-indigo-300",
    selectedBg: "bg-indigo-100 border-indigo-300",
  },
  {
    name: "gamepad-2",
    icon: Gamepad2,
    textColor: "text-pink-500",
    hoverBg: "hover:bg-pink-100 hover:border-pink-300",
    selectedBg: "bg-pink-100 border-pink-300",
  },
  {
    name: "briefcase",
    icon: Briefcase,
    textColor: "text-cyan-500",
    hoverBg: "hover:bg-cyan-100 hover:border-cyan-300",
    selectedBg: "bg-cyan-100 border-cyan-300",
  },
  {
    name: "banknote",
    icon: Banknote,
    textColor: "text-emerald-500",
    hoverBg: "hover:bg-emerald-100 hover:border-emerald-300",
    selectedBg: "bg-emerald-100 border-emerald-300",
  },
  {
    name: "plane",
    icon: Plane,
    textColor: "text-sky-500",
    hoverBg: "hover:bg-sky-100 hover:border-sky-300",
    selectedBg: "bg-sky-100 border-sky-300",
  },
  {
    name: "package",
    icon: Package,
    textColor: "text-amber-500",
    hoverBg: "hover:bg-amber-100 hover:border-amber-300",
    selectedBg: "bg-amber-100 border-amber-300",
  },
];
